### ISSUE TITLE
[SR] IFA Reports (distribution and consumption)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#102]
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1123724563&range=62:62

**Comment by nupoorkhandelwal** [comment]
https://reporting.avniproject.org/question/1493

**Comment by garimadosar5** [comment]
QA Notes - 
- Need to add one more row in both the rows. - "Adolescent taking 0 tablets".
Right now sum is not matching to total adolescent who received IFA.
