### ISSUE TITLE
[SR][Support] Data fixes for records.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#106]
Visit scheduling - https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1928110045

https://avni.freshdesk.com/a/tickets/1036
**- Visits are not scheduled properly for some of the records.**
- [x] 1. Name - Kiran somabhai Vasava
Quartely Visit is not getting scheduled. Currently, a severe malnutrition followup for 13-01-2021. but no quarterly or end-line visit is there.
**Edited Jan 2020 Quaterly, which scheduled ENdline 2020.** 
- [x] 2. Name - Jaytunkumar parsottambhai Vasava
Last quarterly was done on 03-03-2020. after that no visit is getting scheduled.
- [x] 3. Name - Sudhir danubhai Vasava
The last visit was cancelled in April 2020. after that no visit got scheduled.
- [x] 4. Name - Devendra kalpeshbhai Vasava
Quartely Visit is not getting scheduled. Currently, some followups are scheduled.. but no quarterly or end-line visit is there.
 - [x] 5. Name - viralbhai arvindbhai vasava
Quarterly and Annual visits are not getting scheduled. Only one followup visit is scheduled.

**- Multiple visits scheduled**
- [x] 6. Name - Umaben uttam bhai vasava vasava
there were two quarterly scheduled for January. Please check and fix. **Both the visits are already completed.** 
-  [x] 7. Name - Kaushik Dilip Vasava
There are one quarterly in Jan 21 and one for Endline for Mar 21 is scheduled. How endline got scheduled if quarterly Jn 21 is not done?
**Quarterly visit is completed on 06-01-2021 which was scheduled for 01-01-2021. And one endline for march is scheduled. What is not right?And what do we need to fix this**
- [x] 8. Name - divyeshbhai arvindbhai vasava
For this case moderate and severe anaemia both the visits are scheduled. 
**Deleted Moderate Anemia Followup**

**Back dated visits**

- [x] Tulshiben Mukeshbhai - Dharoli Prathmik (Endline generated of 2019, after quarterly done in Feb 2021) **Fixed**
- [x] Kajal Maheshbhai - Avidha Madhyamik (Endline and all visits generated of 2019, after quarterly done in Feb 2021) **ENDLINE VISIT 2021 scheduled**

**Cancel sickle cell -** 
https://avni.freshdesk.com/a/tickets/1038
- [x] 1. Name - rahul suresh vasava
Cancel sickle cell followup and do not schedule any future followup visit.

- [x] 2. Name - Hiral ben bachu bhai Vasava
Cancel sickle cell followup and do not schedule any future followup visit.

**Comment by garimadosar5** [comment]
estimate - 4-5 hrs

**Comment by nupoorkhandelwal** [comment]
**Fix --  Updating Visit scheduling to generate Endline Visits on Cancel of Quarterly Visit.**

**Comment by garimadosar5** [comment]
QA Notes - 
 - ![Screen Shot 2021-02-10 at 1.22.47 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/56238b10-9144-4f3a-8efa-799c63367ae0)

Here one quarterly and one Endline is scheduled. These both should not be scheduled together.

- ![Screen Shot 2021-02-10 at 1.23.24 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0da94f70-cc7a-4b9c-a873-8128d45d7101)

If I cancel this quarterly visit, next visit is not getting scheduled.

Case - Rehan Javant

**Comment by nupoorkhandelwal** [comment]
Change is done. Staging sync is not working so moving to on hold for now.

**Comment by garimadosar5** [comment]
QA Notes - 
It is still scheduling endline (it is still taking encounter date-time somewhere) and quarterly together.

![Screen Shot 2021-02-12 at 6.46.15 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/5d49aac2-b3ec-4957-a6df-2b08d508ad0d)

**Comment by garimadosar5** [comment]
QA Notes - 
still not fixed. Endline scheduled for the past.
![Screen Shot 2021-02-13 at 5.47.28 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7e2edd2f-647b-4af1-a15a-3aca2d9ac8e6)

**Comment by nupoorkhandelwal** [comment]
This fix for the records involves changes in the visit scheduling rule. Since the rules are written in old style, the changes are not getting reflected on webapp. So putting this card on hold till the rule changes are available on the webapp.
