### ISSUE TITLE
[SR][Support] Sewa Rural fixes - Reports

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#109]
**REPORT**
- Attendance for each visit. https://reporting.avniproject.org/question/473
1. Endline rows missing.
2. Midline rows missing.
3. In this report - Number is visit done should be **Done out of planned** and then denominator should be **how many were planned**.

- Prevalence of Sickle Cell Anemia report - https://reporting.avniproject.org/question/525
Indicator - Referred (Number seem to be wrong). Total kids with SC are 36 and referred is 78. this cannot be right.
Refer, FE - "Have you been referred?" in Sickle cell Followup form.

- IFA distribution and consumption 
Req doc- https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1123724563&range=66:66
Reports -
1. https://reporting.avniproject.org/question/1493
2. https://reporting.avniproject.org/question/1494

Change - Please change denominators as per given in the requirement sheet.

**Comment by garimadosar5** [comment]
estimate - 4 hrs

**Comment by garimadosar5** [comment]
**QA Notes-** 
Report - https://reporting.avniproject.org/question/525
- counseling done for trait = 100% that means total sickle cell trait = 562
   counseling done for disease = 100% that means total sickle cell disease = 36
i.e total sickle cell positive = 562+36 = 598
but Total adolescent tested - total adolescent sickle cell negative 
= 3090-2508 = 582
Here 16 cases are missing.

**Comment by nupoorkhandelwal** [comment]
For report https://reporting.avniproject.org/question/1493?start_date=2020-10-01&end_date=2021-01-02

Values wont match only when filter duration is small. Else values are matching for bigger time periods. May be due to Annual visits scheduling. Also the mismatch is mostly during 2020.

**Comment by garimadosar5** [comment]
**QA Notes - 2**
Report - https://reporting.avniproject.org/question/525
% is showing more than 100%.

![Screen Shot 2021-02-09 at 12.50.14 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f99b22cc-00e9-45a3-9c63-afbd39320307)

**Comment by garimadosar5** [comment]
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1123724563&range=64:64

Logic is updated. Please check.
