### ISSUE TITLE
[SR][Support] Scheduling issue

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#112]
https://avni.freshdesk.com/a/tickets/1144

- Case - Kajal ben ramesh bhai Vasava
Quarterly 01 Jan 2021 was done on 15 Jan 2021. It schedule endline of 01 March 2020.

- Case - Hetalben chunilalbhai Vasava
Quarterly 01 Jan 2021 was done on 01 Mar 2021. It did not schedule endline of 01 March 2021.

**Comment by vindeolal** [comment]
There was a bug in Endline visit scheduling logic. The rule was taking encounterDateTime for scheduling the rule instead of visit schedule DateTime. Fixed on Staging and Prod.

**Comment by garimadosar5** [comment]
QA Notes - 
- Case "nisha subhasbhai vasava", a quartely visit was scheduled on 01 03 2021 and completed on 15 10 2020. Now If I am editing this visit, it scheduling one quarterly and one endline. Please check.
