### ISSUE TITLE
[SR] Changes in visit schedule

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#119]
ticket - https://avni.freshdesk.com/a/tickets/1219

Annual Visit - 
Scheduled - On enrolment and then second visit onwards on 01 April
Overdue - after 31 July
On Cancel - No change
Endline visit - 
Scheduled - 01 Feb (schedule for the same day if date is between 01 Feb to 30 April)
Overdue - 30 April
On Cancel - No change

Severe Anemia follow up - 
Scheduled - 01 Nov (whenever the next nov is, schedule for the same day if date is between 01 Nov to 30 Nov)
Overdue - 30 Nov
On Cancel - No change

Sickle cell d'se follow-up - 
Scheduled - 
01 Nov (whenever the next nov is, schedule for the same day if date is between 01 Nov to 30 Nov)
Overdue - 30 Nov
On Cancel - No change

Chronic Sickness follow-up - 
Scheduled - 01 Nov (whenever the next nov is, schedule for the same day if date is between 01 Nov to 30 Nov)
Overdue - 30 Nov
On Cancel - No change

Moderate anaemia follow-up - 
Scheduled - 01 Nov (whenever the next nov is, schedule for the same day if date is between 01 Nov to 30 Nov)
Overdue - 30 Nov
On Cancel - No change

Menstrual absenteeism follow-up - 
Scheduled - 01 Nov (whenever the next nov is, schedule for the same day if date is between 01 Nov to 30 Nov)
Overdue - 30 Nov
On Cancel - No change

Severe malnutrition follow-up - 
Scheduled - 01 Nov (whenever the next nov is, schedule for the same day if date is between 01 Nov to 30 Nov)
Overdue - 30 Nov
On Cancel - No change

**Comment by vindeolal** [comment]
- Apart from the above-mentioned changes, the visit scheduling of the Endline is changed a bit. Earlier we used to schedule Quarterly from Feb's endline, now we'll schedule April's Annual.
- Changes are deployed on staging.

-------------Production deployment steps-----------------
- Deploy the rules from CMD
