### ISSUE TITLE
[SR] Offline report

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#121]
Req - https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=660127933

Details are given in the sheet.

**Comment by vindeolal** [comment]
Deployed on staging.
Realm query link: https://github.com/avniproject/sewa-rural/commit/500f8c01e41c696d2fbcb2d5ff3c79c25574b96a
