### ISSUE TITLE
[SR] Add Counselling points for Annual and quarterly visits.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#126]
ticket - https://avni.freshdesk.com/a/tickets/1366

Counselling points for Vulnerability should be shown in Annual and Quarterly visit for respective Vulnerability. Vulnerabilities  are given below:
i). Menstrual Disorder
ii). Addiction
iii). Sickle Cell Disease
iv). Severe Anemia
v). Moderate Anemia
vi). Severe Malnutrition
vii). School Dropout
viii). Chronic Sickness
ix). Obesity and Sickle cell Trait (Already showing)
Counselling points will be shown when these vulnerabilities are detected in the Annual or Quarterly visits.
Counselling points - https://docs.google.com/spreadsheets/d/1Lne2kI-W5XPozmLX1_sn5WQ5L3AuN70X/edit#gid=331194079

**Comment by vindeolal** [comment]
Deployed on staging.
Please note Chronic Sickness is not scheduled from Quarterly so have not added counselling for this in the Quarterly visit.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Quarterly visit, obesity counselling points are showing but weight is not taken in quarterly.
Also, chronic sickness counselling is showing even if chronic sickness is not selected.

**Comment by vindeolal** [comment]
- Fixed the "obesity counselling". I could not see the "chronic sickness counselling" showing up.
