### ISSUE TITLE
[SR] Changes/Bugs reported

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#127]
1. Sickle Cell disease should show as RED in the Observation Table - If Sickle cell test is done and the result is Disease then that answer should show in Red in the observation table.
2. For Sickle cell Disease Vulnerability follow up monthly - Currently we have visits scheduled in November month after vulnerability detected. Change it to monthly follow up.
- first followup will be scheduled immediately after annual and 
- second onwards, visit will be scheduled after one month of the previous visit scheduled. 
- And these visits will be over due after 15 days.
3. For Severe Anemia Vulnerability  follow up monthly -Currently we have visits scheduled in Nov after vulnerability detected. Change it to monthly followup till the change in Anemia status. Once it is back to moderate then start scheduling in November month or if HB is normal then stop scheduling any followup visit.
- first followup will be scheduled immediately after annual and 
- second onwards, visit will be scheduled after one month of the previous visit scheduled. 
- And these visits will be over due after 15 days.
4. Report Prevalence of sickle cell Anemia - Indicators "Sickle cell Trait" and "Sickle cell disease", change denominator to "Total tested Adolescent". (Negative + Total Adolescent Trait + Total Adolescent Disease = Total tested Adolescents) https://reporting.avniproject.org/question/525-prevalence-of-sickle-cell-anemia
5. Offline Dashboard - User Jyotsana should have 9 sickle cell disease Adolescents. Currently it is showing 0.
User Jitendra should have 12 sickle cell disease Adolescents.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Point 2 and 3 not done.![Screenshot from 2021-08-25 11-58-45.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/13527185-52f1-4e33-a763-00717d327dfd)
Both sickle cell and severe anemia scheduled for Nov month.

**Comment by vindeolal** [comment]
Fixed
