### ISSUE TITLE
[SR][Support] My Dashboard filter - Standard

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#134]
https://avni.freshdesk.com/a/tickets/1600

- [x] Add Standard in enrolment decision as well and update it each time user fill ay annual format and update the standard there.
- [x] Migrate all the data with latest Standard for all the cases.
- [x] Create a new filter for standard that is on the enrolment standard concept. So that they can see latest standard of the child.

**Comment by nupoorkhandelwal** [comment]
Script for migration --
yes.removed them

https://github.com/avniproject/sewa-rural/blob/master/scripts/add%20Latest%20standard%20to%20enrolment%20decisions
