### ISSUE TITLE
[SR][Report][Bug] Prevalence of Anemia Report 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#48]
https://openchs.freshdesk.com/a/tickets/470

**Comment by vindeolal** [comment]
HB is not taken in every visit. As per the current report we were looking HB in the latest visit (Annual/Quarterly which may or may not be captured) which is causing these low numbers.
Changed the logic to take HB value from the latest visit where it is captured.
Also as mentioned in the ticket there are some individuals for whom HB is never taken (either visit is not done or value is not captured.) so Sum of total % will never be 100.
There are 3104 people enrolled, out of these 3025 people with HB taken at least once and  for 79 HB is never taken.
