### ISSUE TITLE
[SR] Highlight Risk in RED.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#49]
https://openchs.freshdesk.com/a/tickets/377

**Comment by sachsk** [comment]
Deployed in staging

**Comment by garimadosar5** [comment]
QA Notes - 
- Sync is failing -
![Screen Shot 2019-11-14 at 12.43.51 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c08ac9f3-6b7b-4b71-b0fa-30fffaac380f)

**Comment by garimadosar5** [comment]
@sachsk 
This is working, deploy this on production.

**Comment by sachsk** [comment]
Deployed
