### ISSUE TITLE
[SR] End-line Form for March Month

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#57]
- Ticket - https://openchs.freshdesk.com/a/tickets/479

- Ref Doc - 
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit?pli=1#gid=1566431958
(This is the same for as Quarterly visit with one additional question.)

- Schedule an end-line visit on 01-Mar every year.

- Name these end-line forms as end-line 1, end-line 2, ...... so on.
- For the kids' Baseline done in 2018, March 2020 end line will be end line 2 as we have considered midline 2019 Endline 1.

**Comment by garimadosar5** [comment]
QA Notes - 
- Endline visit is not getting scheduled.
- Endline visit should trigger from both Annual and Quarterly visit. Whichever is applicable.

**Comment by vindeolal** [comment]
Visit scheduling from cancellation form added.

**Comment by garimadosar5** [comment]
@vindeolal 
Working, we can deploy it on prod.
