### ISSUE TITLE
[SR][Support]Change in Visit scheduling of Dropout Home Visit.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#58]
Adding a new question in the Annual Visit form "If Dropout, in which year he/she left the school?".  Based on the answer to this question the Dropout visits will be scheduled.

If, Child dropped out before <x months/years>, then do not schedule the dropout visits for that child. 
x>= 1 year

**Comment by sachsk** [comment]
@garimadosar5 
Done.

Deployed on Staging

**Comment by garimadosar5** [comment]
Working on staging.
Deploy this on prod.

**Comment by sachsk** [comment]
@garimadosar5 
Deployed on prod
