### ISSUE TITLE
[SR][Report] Prevalence of Anemia (Change in Status of Anemia)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#61]
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1689078892

**Filter** - Select Baseline Year
##### Aggregated Report - 
Refer the document for report format
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1407248223

##### Line List - Severe Anemia 
- Columns - 
Name - Registration	
Age - Registration	
Gender - Registration	
Address (Intervention Area - Registration	
Baseline Hemoglobin - Annual Visit (Baseline year) - Qus 23.2
No of IFA consumed - Severe Anemia Follow up visit - Qus SA_10
Albendazole received - Quarterly visit (Latest) - Qus 26
No of Vit B12 tablets consumed - Severe Anemia Follow up visit - Qus SA_16
Visited hospital - Severe Anemia Follow up visit (Latest) - Qus SA_6
Endline Hemoglobin - Endline form - Qus 23.2
Total follow up visits done - Total count of follow up visits done for Severe anaemia in a particular adolescent during the baseline and end line years mentioned	

##### Line List - Moderate Anemia 
Name - Registration	
Age - Registration	
Gender - Registration	
Address (Intervention Area - Registration	
Baseline Hemoglobin - Annual Visit (Baseline year) - Qus 23.2
No of IFA received - Moderate Anemia Follow up visit - Qus SA_10
Albendazole received - Quarterly visit (Latest) - Qus 26
No of Vit B12 tablets consumed - Moderate Anemia Follow up visit - Qus SA_16
Visited hospital - Moderate Anemia Follow up visit (Latest)	- Qus SA_6
Endline Hemoglobin - Endline form - Qus 23.2
Total follow up visits done - Total count of follow up visits done for Severe anaemia in a particular adolescent during the baseline and end-line years selected
 

###### Acceptance Criteria - 
-

**Comment by vindeolal** [comment]
Report link : https://reporting.openchs.org/question/625

**Comment by garimadosar5** [comment]
QA Notes - 
- Add `OTHER` Gender also in the table.

**Comment by vindeolal** [comment]
@garimadosar5 
Fixed point 1, Indicators added in case baseline is missed for any individual.
For point 2, we take non-exited individuals, so if the individual is exited it won't show up. In all SR report we are showing all non-exited individuals.

**Comment by garimadosar5** [comment]
- IFA consumed is 0 for all the cases where the baseline year is 2018. Because the Severe anaemia followup encounter was introduced in 2019.
Not sure how we will solve this. because previously we were collecting IFA information only in Annual and quarterly encounter.

**Comment by garimadosar5** [comment]
Avg Time to load - 4 Mins
