### ISSUE TITLE
[SR][Report] Menstrual Hygiene Practices (Change in Hygiene Practices)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#62]
**Filter - ** Select the Baseline year
##### Aggregated Report
For report format refer the document -
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1407248223

For the calculation -
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1689078892

##### Line List
- Columns - 
Name - Registration	
Age - Registration	
Address - Registration	
School going - Annual / Quarterly visit (Latest) - Question 18

##### Acceptance Criteria - 
- Kit Pad for baseline or any end line should not be more than the Adolescent who received the MHM kit in baseline or End line.
- The total sum of % Should be 100.
- Total Adolescents in the table should not more than the total female enrolled in the system.
- Any time total in the end line should not be more than Baseline Adolescent Numbers.
- The total of all the absorbent should not be more than the total number of female Adolescents (Menstruation started).
- All the Cases should be there in the line list for all the indicators of Baseline and End line.
- The percentage should be calculated out of total Adolescent with menstrual started, not Kit received.

##### Test Cases - 

-

**Comment by garimadosar5** [comment]
QA Notes - 
- Line list cases are not showing in the end line 2019.
- End line year 2019 is showing two times for Endline year 1 and Endline 2.
-

**Comment by sachsk** [comment]
The number of  https://reporting.openchs.org/question/492?start_date=2018-01-01&end_date=2018-09-01 these report cant match with new reports because in new reports we have applied a filter to encounter_date, and old report have filters on enrolment date

**Comment by sachsk** [comment]
https://reporting.openchs.org/question/627?year=2019

**Comment by garimadosar5** [comment]
##### QA Notes - 
Time to load -
