### ISSUE TITLE
[SR][Report] School Dropout Ratio

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#63]
##### Aggregated Report - 
**Filter - **
Select Baseline Year
For Format - 
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1407248223
For Calculation - 
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1689078892
##### Line List - 
**Columns - **
Name - Registration	
Age - Registration	
Gender - Registration	
Address - Registration	
Reason for drop out - School drop out home visit - QUS 2
Drop out since when - School drop out home visit - QUS 1

##### Acceptance Criteria - 
- No exited Enrolment
- No Voided Individual
-  The number of Total Adolescents each year (Dropout + Back to School + Data not captured) should be equal to total drop out in the baseline year.
- Count of Male + Female should be equal to Total count for each year and each indicator.
- Data should get filter based on the filter of the Baseline year.

##### Test Cases - 
- Dropout number in Baseline -
    • Fill in the first annual visit that kid has dropped out of the school.
- Back to School Number in Endline - 
   •  put "not joined school" in all the Home followup visit.
   • Put "Joined school but not attending" in Home followup Visit.
 - Dropout Number in Endline - 
   • If the health worker captures that in Endline kid has dropped out the school but he/she was in school during baseline.
- What if the unplanned visit is done for Baseline or any end line.

**Comment by garimadosar5** [comment]
QA Notes - 
- For End line 2019 or after that, all the rows are zero. for midline/end line 2019, some data should be there. at least the number should be there for the indicator "data not captured".

**Comment by vindeolal** [comment]
1. Fixed
2. There is no school drop out cases for 2018 baseline.
3. Fixed
