### ISSUE TITLE
[SR][Report] Line List of Chronic Sickness

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#65]
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1689078892

##### Logic -
 - All the cases where Annual Visit Qus 50, answered other than "No Problem".
- On the start date and end date filter, it should filter the cases that were enrolled in the program in the selected time range.
- If the date is not selected then show the list of Adolescent with any kind of chronic sickness.
- If there is more than one sickness for one individual, show them as comma-separated.

##### Columns -
Name - Registration	
Age - Registration	
Gender - Registration	
Address - Registration	
School going - Latest annual / Quarterly visit - Qus 18
Chronic Sickness - Latest annual visit - Qus 50
Visited Hospital - Chronic Sickness follow up visit - Qus CS_3
Taking treatment - Chronic Sickness follow up visit - Qus CS_4
Cured - Chronic Sickness follow up visit - Qus CS_9
Reason for not cured - Chronic Sickness follow up visit - Qus CS_10

##### Filters -
- Start Date
- End Date
- Chronic Sickness

##### Acceptance Criteria - 
- No Exited Enrolment
- No Voided Individual
- No Duplicates
- All the cases with any chronic sickness should be there in the list.

**Comment by sachsk** [comment]
@garimadosar5

**Comment by garimadosar5** [comment]
QA Notes - 
- https://reporting.openchs.org/question/633 - This Line list of chronic sickness should be linked to this report - https://reporting.openchs.org/question/472.
