### ISSUE TITLE
[SR][Reports] Line List of Adolescent with Menstrual Disorder

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#68]
Ref Doc - 
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1689078892

##### Logic - 
- Annual/Quarterly - Question 46. if any option is selected other than "No Problem".
- Start date and end date filter will be applicable on the enrolment date.
- If the date is not selected then show the list of Adolescent with any kind of menstrual disorder.

##### Columns - 
Name - 	Registration	
Age	 - Registration	
Address- Registration	
School going - Annual / Quarterly visit (Latest) - Qus 18
Remain absent in school - Annual / Quarterly visit (Latest)	- Qus 48
Absent days - Annual / Quarterly visit (Latest) - Qus 48.2
Disorder	- Annual / Quarterly visit (Latest) - Qus 46
Encounter Date - Encounter date (Annual/Quarterly)

##### Filters - 
- Start Date 
- End Date
- Disorder

##### Acceptance Criteria - 
-  Exited Cases should not be included.
- The voided individual should not be included.
- No duplicate case.
- The total number of rows should not be greater than the number of Adolescent with Menstruation started.

**Comment by sachsk** [comment]
@garimadosar5 

https://reporting.openchs.org/question/635

**Comment by garimadosar5** [comment]
QA Notes - 
- On filter can we apply `like` because there will be cases where more than one disorder will be applicable. So if I apply a filter those cases do not include in the list.
- The number is not matching with the report https://reporting.openchs.org/question/467

**Comment by sachsk** [comment]
https://reporting.openchs.org/question/647

**Comment by garimadosar5** [comment]
Report - 
https://reporting.openchs.org/question/647
