### ISSUE TITLE
[SR][Report][Support] Malnutrition Numbers are not matching.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#74]
Tickets - https://avni.freshdesk.com/a/tickets/554

Reports - 
- https://reporting.openchs.org/question/491 - In this report, Severe malnourished itself is 973. 
- https://reporting.openchs.org/question/463 - In this report all the problems are 354 including severe malnourished. 

- This number should match as in Severe malnourished (#491) should be less than the number of total problems (#463) (Severe malnourished is the part of total problems.) 
- And BMI is calculated only in Annual visit.

**Comment by vindeolal** [comment]
Fixed report https://reporting.openchs.org/question/463
