### ISSUE TITLE
[SR][Support] Endline form questions are missing

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#77]
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1566431958

Question - 20, 21, 22, 23.1, 23.2 are missing in the form.

**Comment by sachsk** [comment]
@garimadosar5 
Q23.2 And Q23.1 are already there
