### ISSUE TITLE
[SR][Report][Support] Few reports are not working.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#89]
Ticket - 
https://avni.freshdesk.com/a/tickets/718

Reports
https://reporting.avniproject.org/question/737 **DONE**
https://reporting.avniproject.org/question/647 **DONE**
https://reporting.avniproject.org/question/644 **DONE**
https://reporting.avniproject.org/question/627 **DONE**
https://reporting.avniproject.org/question/625 **DONE**
https://reporting.avniproject.org/question/641 **DONE**
https://reporting.avniproject.org/question/630 **DONE**
https://reporting.avniproject.org/question/113 **DONE**
https://reporting.avniproject.org/question/99 **DONE**
https://reporting.avniproject.org/question/524 **DONE**
https://reporting.avniproject.org/question/468 **DONE**
https://reporting.avniproject.org/question/463 **DONE**
https://reporting.avniproject.org/question/530 **DONE**
https://reporting.avniproject.org/question/531 **DONE**
https://reporting.avniproject.org/question/532 **DONE**
https://reporting.avniproject.org/question/533 **DONE**
https://reporting.avniproject.org/question/529 **DONE**
https://reporting.avniproject.org/question/492 **DONE**
https://reporting.avniproject.org/question/490 **DONE**
https://reporting.avniproject.org/question/472 **DONE**
https://reporting.avniproject.org/question/491 **DONE**
https://reporting.avniproject.org/question/467 **DONE**
https://reporting.avniproject.org/question/525 **DONE**
https://reporting.avniproject.org/question/497 **DONE**
https://reporting.avniproject.org/question/526 **DONE**

**Comment by vindeolal** [comment]
Deployed the missing views. For the other reports, where we create tmp table, we either need to downgrade Metabase or rewrite these reports so that it does not create the tmp table.

**Comment by vindeolal** [comment]
Fixed the function that was creating the temp tables.

**Comment by garimadosar5** [comment]
QA Notes - 
- There is still an error in these reports.

**Comment by vindeolal** [comment]
@garimadosar5 Again someone dropped those views. I have redeployed the views you can check now.

**Comment by garimadosar5** [comment]
@vindeolal 
Indicator based reports are taking too long to open. giving this message - "your question took too long".

**Comment by vindeolal** [comment]
@garimadosar5 We have not done any query changes right now. We'll be moving these reports to Jasper soon. And I think only one of the indicator report does not load, rest all reports returns after sometime.
