### ISSUE TITLE
Void the performed visit, and schedule a new visit

### ISSUE THREAD

**Issue by vindeolal** [avniproject/sewa-rural#94]
https://avni.freshdesk.com/a/tickets/787

**Comment by sachsk** [comment]
Details shared are incorrect.

User with this name "Rasila Manhar Vasava" does not exist in the database.

There is one user  "Rasila ben margiya bhai Vasava" for whom  there is no annual visit scheduled for next year and also there is no completed visit on 7th October

**Comment by hithacker** [comment]
@garimadosar5 @sachsk Now that Sewa Rural sync is working fine, can we get this done?

**Comment by sachsk** [comment]
@garimadosar5  User with this name "Rasila Manhar Vasava" does not exist in the database

**Comment by garimadosar5** [comment]
Closing this card as the ticket has been closed by the client.
